export const DEMO_PETS = [
  {
    _id: "demo-luna",
    name: "Luna",
    title: "Spokojna kotka szuka parapetu i kochającego domu",
    description: "Czuła, ciekawska i cicha. Luna kocha drzemki w słońcu oraz zabawę piórkiem wieczorem.",
    species: "Kot",
    breed: "Europejski krótkowłosy",
    ageMonths: 10,
    gender: "Female",
    size: "Small",
    color: "Szary",
    coatLength: "Short",
    healthStatus: ["Vaccinated", "Neutered", "Microchipped"],
    adoptionFee: 250,
    adoptionStatus: "Available",
    personality: ["Spokojna", "Towarzyska"],
    images: ["https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=900&q=80"],
    location: { type: "Point", coordinates: [21.0122, 52.2297], city: "Warszawa" },
    status: "Approved",
    type: "adoption",
    isUrgent: false,
    createdAt: "2026-09-08T10:00:00.000Z",
    shelter: { name: "Schronisko na Paluchu" },
  },
  {
    _id: "demo-burek",
    name: "Burek",
    title: "Energiczny labrador gotowy na rodzinne spacery",
    description: "Wesoły, posłuszny i świetny z dziećmi. Burek potrzebuje aktywnego domu z ogrodem albo długimi spacerami.",
    species: "Pies",
    breed: "Labrador retriever",
    ageMonths: 36,
    gender: "Male",
    size: "Large",
    color: "Złoty",
    coatLength: "Short",
    healthStatus: ["Vaccinated", "Neutered", "Microchipped"],
    adoptionFee: 450,
    adoptionStatus: "Available",
    personality: ["Playful", "Good with kids", "Good with dogs"],
    images: ["https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=900&q=80"],
    location: { type: "Point", coordinates: [19.9449, 50.0647], city: "Kraków" },
    status: "Approved",
    type: "adoption",
    isUrgent: false,
    createdAt: "2026-09-07T09:00:00.000Z",
    shelter: { name: "Krakowskie Towarzystwo Opieki nad Zwierzętami" },
  },
  {
    _id: "demo-mila",
    name: "Mila",
    title: "Puszysta maine coon o łagodnym charakterze",
    description: "Duża, dostojna kotka, która lubi towarzystwo ludzi. Nie wymaga ogrodu — wystarczy kanapa i drapak.",
    species: "Kot",
    breed: "Maine Coon",
    ageMonths: 48,
    gender: "Female",
    size: "Medium",
    color: "Rudy",
    coatLength: "Long",
    healthStatus: ["Vaccinated", "Neutered"],
    adoptionFee: 300,
    adoptionStatus: "Available",
    personality: ["Calm", "Good with kids"],
    images: ["https://images.unsplash.com/photo-1574158622682-e40e69881006?auto=format&fit=crop&w=900&q=80"],
    location: { type: "Point", coordinates: [18.6466, 54.352], city: "Gdańsk" },
    status: "Approved",
    type: "adoption",
    isUrgent: false,
    createdAt: "2026-09-06T14:00:00.000Z",
    shelter: { name: "Schronisko w Gdańsku" },
  },
  {
    _id: "demo-reksio",
    name: "Reksio",
    title: "Młody mieszaniec, idealny pierwszy pies",
    description: "Uczący się świata, bardzo przywiązany. Reksio szybko łapie komendy i lubi zabawę w aportowanie.",
    species: "Pies",
    breed: "Mieszaniec",
    ageMonths: 18,
    gender: "Male",
    size: "Medium",
    color: "Brązowy",
    coatLength: "Medium",
    healthStatus: ["Vaccinated", "Microchipped"],
    adoptionFee: 200,
    adoptionStatus: "Available",
    personality: ["Playful", "Loyal"],
    images: ["https://images.unsplash.com/photo-1543466835-00a390d81cc5?auto=format&fit=crop&w=900&q=80"],
    location: { type: "Point", coordinates: [17.0385, 51.1079], city: "Wrocław" },
    status: "Approved",
    type: "adoption",
    isUrgent: true,
    createdAt: "2026-09-05T11:00:00.000Z",
    shelter: { name: "TOZ Wrocław" },
  },
  {
    _id: "demo-kicia",
    name: "Kicia",
    title: "Spokojna seniorka szuka ciepłego domu na emeryturę",
    description: "Cicha, zadbana i przyzwyczajona do mieszkania. Kicia chce tylko kanapy, miski i spokojnych wieczorów.",
    species: "Kot",
    breed: "Perski",
    ageMonths: 108,
    gender: "Female",
    size: "Small",
    color: "Biały",
    coatLength: "Long",
    healthStatus: ["Vaccinated", "Neutered", "Microchipped"],
    adoptionFee: 0,
    adoptionStatus: "Available",
    personality: ["Calm"],
    images: ["https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=900&q=80"],
    location: { type: "Point", coordinates: [16.9252, 52.4064], city: "Poznań" },
    status: "Approved",
    type: "adoption",
    isUrgent: false,
    createdAt: "2026-09-04T08:00:00.000Z",
    shelter: { name: "Schronisko w Poznaniu" },
  },
  {
    _id: "demo-fafik",
    name: "Fafik",
    title: "Beagle pełen energii, kocha tropienie i zabawę",
    description: "Wesoły, głośny i bardzo towarzyski. Fafik najlepiej odnajdzie się w domu, gdzie ktoś dużo chodzi na spacery.",
    species: "Pies",
    breed: "Beagle",
    ageMonths: 8,
    gender: "Male",
    size: "Medium",
    color: "Tricolor",
    coatLength: "Short",
    healthStatus: ["Vaccinated"],
    adoptionFee: 350,
    adoptionStatus: "Available",
    personality: ["Playful", "Good with dogs"],
    images: ["https://images.unsplash.com/photo-1505628346881-b72b27e84530?auto=format&fit=crop&w=900&q=80"],
    location: { type: "Point", coordinates: [19.455, 51.7592], city: "Łódź" },
    status: "Approved",
    type: "adoption",
    isUrgent: false,
    createdAt: "2026-09-03T16:00:00.000Z",
    shelter: { name: "Schronisko Łódź" },
  },
  {
    _id: "demo-bianca",
    name: "Bianca",
    title: "Mądra border collie szuka aktywnego opiekuna",
    description: "Uczy się błyskawicznie i kocha zadania. Bianca będzie szczęśliwa z osobą, która lubi bieganie albo agility.",
    species: "Pies",
    breed: "Border collie",
    ageMonths: 30,
    gender: "Female",
    size: "Medium",
    color: "Czarno-biały",
    coatLength: "Medium",
    healthStatus: ["Vaccinated", "Neutered", "Microchipped"],
    adoptionFee: 400,
    adoptionStatus: "Available",
    personality: ["Smart", "Active"],
    images: ["https://images.unsplash.com/photo-1503256207526-529f2ea241d7?auto=format&fit=crop&w=900&q=80"],
    location: { type: "Point", coordinates: [22.5684, 51.2465], city: "Lublin" },
    status: "Approved",
    type: "adoption",
    isUrgent: false,
    createdAt: "2026-09-02T12:00:00.000Z",
    shelter: { name: "Schronisko w Lublinie" },
  },
  {
    _id: "demo-tofik",
    name: "Tofik",
    title: "Brytyjczyk o złotym sercu, lubi ciszę i głaskanie",
    description: "Niezależny, ale bardzo przywiązany do swoich ludzi. Tofik pasuje do mieszkania i spokojnego trybu życia.",
    species: "Kot",
    breed: "Brytyjski krótkowłosy",
    ageMonths: 14,
    gender: "Male",
    size: "Medium",
    color: "Niebieski",
    coatLength: "Short",
    healthStatus: ["Vaccinated", "Neutered"],
    adoptionFee: 280,
    adoptionStatus: "Available",
    personality: ["Calm", "Affectionate"],
    images: ["https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?auto=format&fit=crop&w=900&q=80"],
    location: { type: "Point", coordinates: [19.0238, 50.2649], city: "Katowice" },
    status: "Approved",
    type: "adoption",
    isUrgent: false,
    createdAt: "2026-09-01T10:00:00.000Z",
    shelter: { name: "Śląskie Schronisko" },
  },
];

export const getDemoPetById = (id) => DEMO_PETS.find((pet) => pet._id === id) || null;

export const mergeWithDemoPets = (apiPets = [], limit) => {
  const real = (Array.isArray(apiPets) ? apiPets : []).filter((pet) => pet && pet.type !== "food_donation");
  const used = new Set(real.map((pet) => String(pet.name || "").toLowerCase()));
  const extra = DEMO_PETS.filter((pet) => !used.has(pet.name.toLowerCase()));
  const merged = [...real, ...extra];
  return typeof limit === "number" ? merged.slice(0, limit) : merged;
};
